remote_theme: sighingnow/jekyll-gitbook
title: The Martian Roadtrip
description: Bookmark this to keep an eye on my project updates!
toc:
    enabled: true


collections:
  data:
    output: true
    permalink: /:collection/:path/
  pages:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - posts
  - data
  - pages
