remote_theme: sighingnow/jekyll-gitbook
title: The Martian Roadtrip
description: Bookmark this to keep an eye on my project updates!
toc:
    enabled: true


collections:
  pages:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - posts
  - pages
  - others
